



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package kasirfix;

import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author FLEX5
 */
public class DashboardAdmin extends javax.swing.JFrame {
    UserProfile up;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();
    public String nama_lengkap;
//    if (up == null)
    public DashboardAdmin() {
        initComponents();
        k.connect();
    }
    class user {
            String nama_lengkap;
            
            public user (String nama_lengkap){
                this.nama_lengkap = nama_lengkap;
            }
        }
    public DashboardAdmin(UserProfile up) {
        this.up = up;
        initComponents();
        k.connect();
        getProfile(up); 
        
//        
        user u = null;
//        
        if (up != null){
            if (up.getNama_lengkap() == null || up.getNama_lengkap().isEmpty()) {
            TxtNamaUser.setText("Pengguna tidak ditemukan");
            } else {
                TxtNamaUser.setText(up.getNama_lengkap());
                nama_lengkap = up.getNama_lengkap();
                u = new user(nama_lengkap);
            } 
        }else {
            TxtNamaUser.setText(u.nama_lengkap);
        }
        
             
    } 
    public void getProfile(UserProfile up) {
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM profil WHERE id_akun=?;");
            if (up != null) {
                this.stat.setInt(1, up.getId_akun());
            } else {
                System.out.println("UserProfile null! Tidak dapat mengambil profil.");
                return;
            }
            this.rs = this.stat.executeQuery();

            if (!rs.next()) {
                System.out.println("Tidak ada data profil ditemukan untuk ID Akun: " + up.getId_akun());
            } else {
                do {
                    up.setNama_lengkap(rs.getString("nama_lengkap"));
                    up.setAlamat(rs.getString("alamat"));
                    up.setId_profil(rs.getInt("id_profil"));
                    up.setNo_hp(rs.getString("nomor_telepon"));
                } while (rs.next());
                System.out.println("Profil berhasil dimuat: " + up.getNama_lengkap());
            }
        } catch (Exception e) {
            e.printStackTrace();  // Tampilkan kesalahan jika ada
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtNamaUser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tampilUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 50));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Custom-Icon-Design-Pretty-Office-11-Shop.64.png"))); // NOI18N
        jLabel1.setText("TOKO KITA");

        TxtNamaUser.setBackground(new java.awt.Color(0, 153, 204));
        TxtNamaUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        TxtNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        TxtNamaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Elegantthemes-Beautiful-Flat-Profile.32.png"))); // NOI18N
        TxtNamaUser.setText("Depi Vitriyana");
        TxtNamaUser.setBorder(null);
        TxtNamaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TxtNamaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaUserActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Custom-Icon-Design-Pretty-Office-6-Logout.32.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(TxtNamaUser)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TxtNamaUser)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tampilUser.setText("users");
        tampilUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tampilUser)
                .addContainerGap(591, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tampilUser)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNamaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaUserActionPerformed
        if (up != null) {
            this.dispose();
            DetailProfil dp = new DetailProfil(up);
            dp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Data profil tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TxtNamaUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tampilUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ListUser lu = new ListUser(up);
        lu.setVisible(true);
    }//GEN-LAST:event_tampilUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TxtNamaUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tampilUser;
    // End of variables declaration//GEN-END:variables

    private void Logout() {
        int response = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus user ini?", 
                "hapus", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION){
            this.setVisible(false);
            Login l = new Login();
            l.setVisible(true);
        } else {
            System.out.println("Dialog ditutup");
        }
    }

}
