/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirfix;


import javax.swing.JOptionPane;

/**
 *
 * @author FLEX5
 */
public class DetailProfil extends javax.swing.JFrame {
    
    UserProfile up = new UserProfile();

    /**
     * Creates new form DetailProfil
     */
    private String RoleLogin;
//    private PreparedStatement stat;
//    private ResultSet rs;
//    private int userId;  // ID pengguna yang diterima dari halaman login
//    private String NamaLogin;
//    Koneksi k = new Koneksi();

    public DetailProfil() {
//        this.up = new UserProfile();
        initComponents();
    }
    
    public DetailProfil(UserProfile up) {
    this.up = up;  // Gunakan objek UserProfile yang dikirim
    initComponents();        
    
    // Set nilai dari UserProfile ke komponen UI
    TxtNamaUser.setText(up.getNama_lengkap());
    TxtAlamat.setText(up.getAlamat());
    TxtNo.setText(up.getNo_hp());
    
    System.out.println(up.getId_akun());
    // Debugging untuk memastikan data dikirim dengan benar
    System.out.println("Nama: " + up.getNama_lengkap());
    System.out.println("Alamat: " + up.getAlamat());
    System.out.println("No HP: " + up.getNo_hp());
    }
//        private void getProfil() {
//        try {
//            String query = "SELECT * FROM profil WHERE id_akun=" + this.userId + ";";
//            System.out.println(query);
//            System.out.println("ID User: " + this.userId);  // Pastikan id benar
//
//            this.stat = k.getCon().prepareStatement(query);
//            this.rs = this.stat.executeQuery();
//            
//            if(rs.next()){
//                System.out.println(rs.getString("nama_lengkap"));
//                System.out.println(rs.getString("alamat"));
//                System.out.println(rs.getString("nomor_telepon"));
//                
//                TxtNamaUser.setText(rs.getString("nama_lengkap"));
//                TxtAlamat.setText(rs.getString("alamat"));
//                TxtNo.setText(rs.getString("nomor_telepon"));
//                NamaLogin = rs.getString("nama_lengkap");
//                pack();
//            }else {
//                System.out.println("data tidak ditemukan");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Gagal memuat profil: " + e.getMessage());
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaUser = new javax.swing.JLabel();
        TxtNo = new javax.swing.JLabel();
        TxtAlamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profil");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("PROFIL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 283, 28, 324);
        jPanel1.add(jLabel1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ionic-Ionicons-Arrow-back-circle-sharp.32.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 28, 28, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Custom-Icon-Design-Pretty-Office-8-User-blue.32.png"))); // NOI18N
        jLabel2.setText("Nama       :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Paomedia-Small-N-Flat-Phone.32.png"))); // NOI18N
        jLabel3.setText("No HP      :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconshock-Vista-General-House.32.png"))); // NOI18N
        jLabel4.setText("Alamat    :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 204, -1, -1));

        TxtNamaUser.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TxtNamaUser.setText(" ");
        jPanel3.add(TxtNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 57, 210, -1));

        TxtNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TxtNo.setText("jLabel5");
        jPanel3.add(TxtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 135, 210, -1));

        TxtAlamat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TxtAlamat.setText("jLabel5");
        jPanel3.add(TxtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 209, 210, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.ipady = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(79, 164, 85, 128);
        jPanel2.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        System.out.println(RoleLogin);
        
        if(up.getRole().equals("Admin")){
//            this.setVisible(false);
            this.dispose();
            DashboardAdmin da = new DashboardAdmin(up);
            da.setVisible(true);
        }else if(up.getRole().equals("Kasir")){
             this.dispose();
            DashboardKasir da = new DashboardKasir(up);
            da.setVisible(true);
        }else if(up.getRole().equals("Owner")){
             this.dispose();
            DashboardKasir da = new DashboardKasir(up);
            da.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxtAlamat;
    private javax.swing.JLabel TxtNamaUser;
    private javax.swing.JLabel TxtNo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables


}
